### ISSUE TITLE
Return unmasked value immediate

### ISSUE THREAD

**Issue by GamingMaker** [raphadesa/BlazorInputMask#28]
Hello,

i'm using this implementation for one of my input fields but i got the issue, that i want the raw value without the masking chars.
I know it's possible since you had an open issue regarding this:
https://github.com/raphadesa/BlazorInputMask/issues/11

My problem is: i want to bind to the unmasked value, since it will be stored unmasked in the database. E.g.: date 31.12 should be stored like 3112.
The next main thing is: i want this immediately. With every input the validation should be updated immediately. You therefor have the "validateOnKeyPress". I just don't know how to bind it to the raw value.. The linked issue is already a bit old and since then the code has changed a lot so this doesn't work anymore. Can you explain me how i can do this in a good way? I only want to bind to the raw value, I don't care for the other value. 
Thanks in advance

**Comment by raphadesa** [comment]
Hello GamingMaker,

Unfortunately this is not the way the component works, you may achieve your goal of getting the raw value by replacing the resulting value against your placeholder characters, or by using RegEx, as I have no plans to implement such functionality.

If you need a custom implementation you may always modify the component to fit your needs.

Please also check Radzen or MudBlazor as they also have quite powerful mask components.

Regards,

Raphaël
________________________________
De : GamingMaker ***@***.***>
Envoyé : Thursday, February 22, 2024 10:25:26 AM
À : raphadesa/BlazorInputMask ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [raphadesa/BlazorInputMask] Return unmasked value immediate (Issue #28)


Hello,

i'm using this implementation for one of my input fields but i got the issue, that i want the raw value without the masking chars.
I know it's possible since you had an open issue regarding this:
#11<https://github.com/raphadesa/BlazorInputMask/issues/11>

My problem is: i want to bind to the unmasked value, since it will be stored unmasked in the database. E.g.: date 31.12 should be stored like 3112.
The next main thing is: i want this immediately. With every input the validation should be updated immediately. You therefor have the "validateOnKeyPress". I just don't know how to bind it to the raw value.. The linked issue is already a bit old and since then the code has changed a lot so this doesn't work anymore. Can you explain me how i can do this in a good way? I only want to bind to the raw value, I don't care for the other value.
Thanks in advance
