### ISSUE TITLE
Is possible to use without a bind-value ?

### ISSUE THREAD

**Issue by omarceloribeiro** [raphadesa/BlazorInputMask#29]
I tried to use the component without a bind-value, I just need the on change event so I can execute a fetch, but it gives error. 

`Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: BlazorInputMask.InputMask requires a value for the 'ValueExpression' parameter. Normally this is provided automatically when using 'bind-Value'.
System.InvalidOperationException: BlazorInputMask.InputMask requires a value for the 'ValueExpression' parameter. Normally this is provided automatically when using 'bind-Value'.`

seems that the ValueExpression is required.

scenario:
In blazor default component was not possible to use bind-value along with onchange. one exclude the other. so I was using just the onchange, without the bind-value

thank you

**Comment by raphadesa** [comment]
Hello Marcelo,

Instead of using @bind-Value could you try to manually set the Value, and wire an `EventCallback<string>` to ValueExpression ? 

Regards,

Raphaël

**Comment by omarceloribeiro** [comment]
Hi, thank you, passing a function to ValueExpression that just return a string, it worked but also required a variable, because I cant pass a string inside the "" attribute. doesn't compile. ValueExpression="() =>"""

so  I endup creating a variable to use in @bind-Value, it is fine, seems good.
great component btw, simple to use and install, much easier than that ones in those big libraries.
thank you so much!

**Comment by raphadesa** [comment]
Sorry, I meant ValueChanged not ValueExpression.

Glad to know you appreciate the component !

Regards,

Raphael
________________________________
De : Marcelo Ribeiro ***@***.***>
Envoyé : Wednesday, February 28, 2024 6:00:27 AM
À : raphadesa/BlazorInputMask ***@***.***>
Cc : Raphaël Desalbres ***@***.***>; Comment ***@***.***>
Objet : Re: [raphadesa/BlazorInputMask] Is possible to use without a bind-value ? (Issue #29)


Hi, thank you, passing a function to ValueExpression that just return a string, it worked but also required a variable, because I cant pass a string inside the "" attribute. doesn't compile. ValueExpression="() =>"""

so I endup creating a variable to use in @bind-Value, it is fine, seems good.
great component btw, simple to use and install, much easier than that ones in those big libraries.
thank you so much!
